version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    env_file: ./.env
    environment:
      - DB_HOST=mysql_server
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DB_NAME
      - DB_PORT=$MYSQL_PORT
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=cityweather
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
volumes:
  db: